//小明有 5 张数字卡片，上面分别为数字 1， 2， 3， 6， 9。小明想用这 5 张数字卡片组成一个最大的 5 位
//素数，这个五位数是_______。
//编程：任意输入5个数字，将它们组合为最大的5位素数输出。如果不存在5位素数，则输出ERROR。
#include<stdio.h>
int main(){
	int x[5],i=0,j=0,y[120],z[5],n=10000,m=0,k=0,s=0,a=0,b=0,c=0,d=0,e=0,l=0;
	while(i<5){
		scanf("%d",&x[i]);
		i++;
	}
	i=0;
	while(a<5){
		b=0;
		while(b<5){
			if(b!=a){
				c=0;
				while(c<5){
					if(c!=a&&c!=b){
						d=0;
						while(d<5){
							if(d!=a&&d!=b&&d!=c){
								e=0;
								while(e<5){
									if(e!=a&&e!=b&&e!=c&&e!=d){
										y[i]=x[a]*10000+x[b]*1000+x[c]*100+x[d]*10+x[e];
										i++;
										k=i;
										d++;
										break;
									}
									else{
										e++;
									}
								}
							}
							else{
								d++;
							}
							if(0==k%2&&0!=k){
								c++;
								l=l+2;
								k=0;
								break;
							}
						}
					}
					else{
						c++;
					}
					if(0==l%6&&0!=l){
						m=m+6;
						l=0;
						b++;
						break;
					}
				}
			}
			else{
				b++;
			}
			if(0==m%24&&0!=m){
				m=0;
				a++;
				break;
			}
		}
	}
	i=0,s=0;
	while(i<120){
		j=0,n=2;
		while(n<y[i]){
			k=y[i]%n;
			if(k!=0){
				j++,n++;
			}
			else{
				break;
			}
		}
		if(j==y[i]-2&&s<y[i]){
			s=y[i];
		}
		i++;
	}
	if(9999<s&&s<100000){
		printf("%d\n",s);
	} 
	else{
		printf("ERROR\n");
	}
	return 0;
}
